/**
 * Renders a scenario's survey plate to SVG, headlessly.
 *
 * The images in the README are generated by this script rather than screenshotted,
 * which keeps them reproducible, small, diffable in review, and honest: they are
 * drawn from the same library the game runs on, so a plate showing A* examining 573
 * tiles cannot drift from what A* actually does. Regenerate with `pnpm docs:plates`.
 *
 * It also exercises the claim the architecture rests on — that everything below the
 * client is headless. This script imports `@rationauts/sim` in plain Node, with no
 * DOM anywhere.
 */
import { positionKey, type Position, type WorldState } from '@rationauts/core';
import { createRun, type PlannerId, type PlanTelemetry, type Scenario } from '@rationauts/sim';
import { SCENARIOS, scenarioById } from '@rationauts/sim';
import { mkdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { PALETTE, TERRAIN_FILL } from '../src/palette.js';

const TILE = 18;
const CONTOUR_BANDS = 7;

/**
 * Runs a scenario to completion and returns its most substantial plan.
 *
 * Taking the first plan would be simpler and useless: the opening leg is usually a
 * two-tile hop to the nearest grove, which illustrates nothing. The largest plan of
 * the run is the one that actually shows the planner working — typically the long
 * haul from a grove to the depot — and "largest" is a well-defined choice rather than
 * a flattering one, since it is applied identically to every planner.
 */
function largestPlan(
  scenario: Scenario,
  planner: PlannerId,
): { state: WorldState; plan: PlanTelemetry | null } {
  const run = createRun(scenario, planner);
  let best: { state: WorldState; plan: PlanTelemetry | null } = {
    state: run.snapshot().state,
    plan: null,
  };
  const seen = new Set<PlanTelemetry>();

  let snapshot = run.snapshot();
  while (!snapshot.finished) {
    snapshot = run.tick();
    for (const plan of snapshot.plans.values()) {
      if (plan === null || seen.has(plan)) continue;
      seen.add(plan);
      if (plan.explored.length > (best.plan?.explored.length ?? 0)) {
        best = { state: snapshot.state, plan };
      }
    }
  }
  return best;
}

function escapeAttribute(value: string): string {
  return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/"/g, '&quot;');
}

function renderPlate(scenario: Scenario, planner: PlannerId): string {
  const { state, plan } = largestPlan(scenario, planner);
  const { grid } = state;
  const width = grid.width * TILE;
  const height = grid.height * TILE;
  const parts: string[] = [];

  // One background rect, then only the tiles that differ from it. A rect per tile
  // would triple the file size for no visible gain.
  parts.push(
    `<rect width="${String(width)}" height="${String(height)}" fill="${TERRAIN_FILL.plains}"/>`,
  );
  for (let y = 0; y < grid.height; y++) {
    for (let x = 0; x < grid.width; x++) {
      const terrain = grid.tiles[y * grid.width + x];
      if (terrain === undefined || terrain === 'plains') continue;
      parts.push(
        `<rect x="${String(x * TILE)}" y="${String(y * TILE)}" width="${String(TILE)}" height="${String(TILE)}" fill="${TERRAIN_FILL[terrain]}"/>`,
      );
    }
  }

  if (plan !== null && plan.explored.length > 0) {
    const firstSeen = new Map<string, number>();
    plan.explored.forEach((position, order) => {
      const key = positionKey(position);
      if (!firstSeen.has(key)) firstSeen.set(key, order);
    });
    const total = plan.explored.length;
    for (const [key, order] of firstSeen) {
      const [rawX = '0', rawY = '0'] = key.split(',');
      const band = Math.floor((order / total) * CONTOUR_BANDS);
      const opacity = (0.34 - band * 0.035).toFixed(3);
      parts.push(
        `<rect x="${String(Number(rawX) * TILE)}" y="${String(Number(rawY) * TILE)}" width="${String(TILE)}" height="${String(TILE)}" fill="${PALETTE.teal}" opacity="${opacity}"/>`,
      );
    }
  }

  // Graticule.
  const lines: string[] = [];
  for (let x = 0; x <= grid.width; x++) {
    lines.push(`M${String(x * TILE)} 0V${String(height)}`);
  }
  for (let y = 0; y <= grid.height; y++) {
    lines.push(`M0 ${String(y * TILE)}H${String(width)}`);
  }
  parts.push(
    `<path d="${lines.join('')}" stroke="${PALETTE.ruleSoft}" stroke-width="1" fill="none"/>`,
  );

  if (plan !== null && plan.route.length > 1) {
    const points = plan.route
      .map(
        (position) =>
          `${String(position.x * TILE + TILE / 2)},${String(position.y * TILE + TILE / 2)}`,
      )
      .join(' ');
    parts.push(
      `<polyline points="${points}" fill="none" stroke="${PALETTE.brass}" stroke-width="2.4" stroke-linejoin="round" stroke-linecap="round" opacity="0.9"/>`,
    );
  }

  const centre = (position: Position): [number, number] => [
    position.x * TILE + TILE / 2,
    position.y * TILE + TILE / 2,
  ];

  for (const node of state.nodes) {
    const [cx, cy] = centre(node.position);
    parts.push(
      `<circle cx="${String(cx)}" cy="${String(cy)}" r="${String(TILE * 0.28)}" fill="none" stroke="#7FB08A" stroke-width="1.6"/>`,
      `<circle cx="${String(cx)}" cy="${String(cy)}" r="${String(TILE * 0.09)}" fill="#7FB08A"/>`,
    );
  }
  for (const depot of state.depots) {
    const [cx, cy] = centre(depot.position);
    const half = TILE * 0.3;
    parts.push(
      `<rect x="${String(cx - half)}" y="${String(cy - half)}" width="${String(half * 2)}" height="${String(half * 2)}" fill="none" stroke="${PALETTE.paper}" stroke-width="1.6"/>`,
      `<path d="M${String(cx - half)} ${String(cy)}H${String(cx + half)}M${String(cx)} ${String(cy - half)}V${String(cy + half)}" stroke="${PALETTE.paper}" stroke-width="1.2"/>`,
    );
  }
  for (const bot of state.bots) {
    const [cx, cy] = centre(bot.position);
    parts.push(
      `<circle cx="${String(cx)}" cy="${String(cy)}" r="${String(TILE * 0.3)}" fill="${PALETTE.brass}" stroke="${PALETTE.ink}" stroke-width="1.4"/>`,
    );
  }

  const examined = plan?.explored.length ?? 0;
  const title = `${scenario.name}, ${planner}: ${String(examined)} tiles examined`;

  return [
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${String(width)} ${String(height)}" width="${String(width)}" height="${String(height)}" role="img" aria-label="${escapeAttribute(title)}">`,
    `<title>${escapeAttribute(title)}</title>`,
    ...parts,
    '</svg>',
    '',
  ].join('\n');
}

const TARGETS: readonly { scenario: string; planner: PlannerId; file: string }[] = [
  { scenario: 'great-plain', planner: 'ucs', file: 'great-plain-uniform-cost.svg' },
  { scenario: 'great-plain', planner: 'astar', file: 'great-plain-astar.svg' },
  { scenario: 'mudflats', planner: 'bfs', file: 'mudflats-breadth-first.svg' },
  { scenario: 'mudflats', planner: 'ucs', file: 'mudflats-uniform-cost.svg' },
];

function main(): void {
  // Resolved from this file rather than the working directory, so the script
  // produces the same output however it is invoked.
  const outputDir = fileURLToPath(new URL('../../../docs/assets/', import.meta.url));
  mkdirSync(outputDir, { recursive: true });

  for (const target of TARGETS) {
    const scenario = scenarioById(target.scenario);
    if (scenario === undefined) {
      throw new Error(
        `Unknown scenario ${target.scenario}. Known: ${SCENARIOS.map((s) => s.id).join(', ')}`,
      );
    }
    const svg = renderPlate(scenario, target.planner);
    writeFileSync(`${outputDir}${target.file}`, svg, 'utf8');
    const examined = /(\d+) tiles examined/.exec(svg)?.[1] ?? '0';
    console.log(`wrote docs/assets/${target.file} (${examined} tiles examined)`);
  }
}

main();
